/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei/useGLTF';

export default function Model(props) {
    const group = useRef();
    const { nodes, materials } = useGLTF('/models/seat.glb');
    return (
        <group ref={group} {...props} dispose={null}>
            <mesh
                material={materials.sillones_COLOR_0}
                geometry={nodes.Cube000.geometry}
                position={[1.6, 0.09, -0.01]}
                rotation={[Math.PI / 2, 0, -3.13]}
            />
            <mesh
                material={materials.sillones_COLOR_0}
                geometry={nodes.Cube001.geometry}
                position={[0.9, 0.06, -0.06]}
                rotation={[Math.PI / 2, 0, -3.13]}
            />
            <mesh
                material={materials.sillones_COLOR_0}
                geometry={nodes.Cube002.geometry}
                position={[-1.07, 0.03, -0.13]}
                rotation={[Math.PI / 2, 0, -3.13]}
            />
        </group>
    );
}

useGLTF.preload('/seat85.glb');
